spring:
  datasource:
    driver-class-name:
    username: sa
    password:
    url: jdbc:h2:file:./hetfoijajjgatas
    initialize: false
  jooq:
    sql-dialect: postgres
vaadin:
  servlet:
    production-mode: true
