spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:./hetfoijajjgatas
    initialize: false
  jooq:
    sql-dialect: h2
vaadin:
  servlet:
    production-mode: true
