CREATE TABLE user (
  username VARCHAR(255) PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE wail (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  content TEXT NOT NULL,
  link VARCHAR(1024) DEFAULT NULL,
  user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (user_id) REFERENCES user(username)
);
